### PR TITLE
Fixed labels in matrix methods so it is consistently (row, col)

### PR DESCRIPTION
**Pull request by estherturner**
Changed the methods in DenseMatrix.cpp and DenseMatrix.h so that they all take (row, col) as arguments, rather than the other way around, and pass the arguments onto Armadillo that way.

### CODE REVIEW

**Comment by jackdunger** [comment]
Hi @estherturner, you should probably do this for the `SparseMatrix` class too for consistency. What do you say?

**Comment by estherturner** [comment]
Oh, of course. That completely slipped my mind.

**Comment by estherturner** [comment]
I've added another commit to do this for the Sparse Matrix class as well. I think the SetComponents method was already written the correct way around, as far as I could tell.

**Comment by jackdunger** [comment]
thanks, merging

**Pull request merged**
