### PR TITLE
Quick fixes

### PR DESCRIPTION
**Pull request by BillyLiggins**
Some quick fixes so I don't forget them. 

1) fixed header guard in scale.h
2) removed counter increment from AddPdfs() in BinnedEDManager. It calls AddPdf() which does the increment aswell.

There is no rush on these.

### CODE REVIEW

**Comment by BillyLiggins** [comment]
This now contains a fix to the systematic.cpp. Now when adding an AxisCollection to the systematic a sparse matrix of size axes.GetNBins x axes.GetNBins.

**Comment by jackdunger** [comment]
Nice catches, is this now ready to merge?

**Comment by BillyLiggins** [comment]
I believe so

**Comment by jackdunger** [comment]
👍

**Pull request merged**
