### PR TITLE
Py bind iii

### PR DESCRIPTION
**Pull request by mjmottram**
Added lots of .wrap files to map classes and methods to python module.  Probably not ready for a merge yet.  Notes (including some apparently unrelated updates):
* Update bin/SConscript to create executable
* Python module auto-installed to python packages directory (if permitted)
* Update to buildhelp to allow optional dependencies (boost & python not required for basic build)
* Make constructors public (ROOTNtuple had private functions, not sure why)
* Not sure why CompositePdf * operator needed to free standing function (can't think of a use case) and it broke the bindings
* No bindings for Heaviside yet (class not fully implemented, python didn't like pure virtual methods)
* No bindings for overloaded methods yet, still figuring out how to implement these.

### CODE REVIEW

**Comment by jackdunger** [comment]
Hi @mjmottram, looking good!
A couple of clarifications:
* "Make constructors public (ROOTNtuple had private functions, not sure why)" root-files and root-trees are not copyable, so the constructors are deliberately private. No implementation makes sense, so the compiler should not synthesise one. 

* "Not sure why CompositePdf * operator needed to free standing function (can't think of a use case) and it broke the bindings" - it's the most common use case. You combine two pdf objects into one composite pdf object - untill they are combined you don't have a composite pdf. In the other use case - i.e. one of the two pdfs is already a composite pdf then you want the multiplication to work regardless of order. 

* What is the executible, just out of interest?

**Comment by mjmottram** [comment]
OK, I can have another look, but building with boost failed when the copy constructor was private.  Same issue with the free method for the operator, I'll have another look at that as well.  I just meant force the compiled executable to have executable permissions (mine weren't by default).

**Comment by mjmottram** [comment]
Noncopyable keyword fixes the ROOTNtuple bindings, and the free * operator was fine all along.  The basic gaussian_smear.py script works for me.  Need to test a bit more and get the overloaded functions implemented.

**Comment by jackdunger** [comment]
Ok thanks, good to know that all works fine. There are a few other c++ changes I don't understand, but won't review until you're done.

**Comment by jackdunger** [comment]
@tsengj10

**Pull request closed without merging**
